---

- name: test if item in f5_ltm_provider is set correctly
  assert:
    that:
      - f5_ltm_provider.server is defined
      - f5_ltm_provider.user is defined
      - f5_ltm_provider.password is defined
      - f5_ltm_provider.port is defined
      - f5_ltm_provider.port is number
      - f5_ltm_provider.port > 0
      - f5_ltm_provider.port < 65536
      - f5_ltm_provider.validate_certs is defined
      - f5_ltm_provider.validate_certs is boolean
    quiet: yes
  when:
    - f5_ltm_provider is defined

- name: test if f5_ltm_partition is set correctly
  assert:
    that:
      - f5_ltm_partition is defined
    quiet: yes

- name: test if f5_ltm_hostname is set correctly
  assert:
    that:
      - f5_ltm_hostname is defined
    quiet: yes

- name: test if f5_ltm_timezone is set correctly
  assert:
    that:
      - f5_ltm_timezone is defined
    quiet: yes

- name: test if f5_ltm_ntp_servers is set correctly
  assert:
    that:
      - f5_ltm_ntp_servers is defined
      - f5_ltm_ntp_servers is iterable
    quiet: yes

- name: test if f5_ltm_nodes is set correctly
  assert:
    that:
      - f5_ltm_nodes is iterable
    quiet: yes
  when:
    - f5_ltm_nodes is defined

- name: test if item in f5_ltm_nodes is set correctly
  assert:
    that:
      - item.name is defined
      - item.host is defined
    quiet: yes
  loop: "{{ f5_ltm_nodes }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - f5_ltm_nodes is defined

- name: test if f5_ltm_pools is set correctly
  assert:
    that:
      - f5_ltm_pools is iterable
    quiet: yes
  when:
    - f5_ltm_pools is defined

- name: test if item in f5_ltm_pools is set correctly
  assert:
    that:
      - item.name is defined
      - item.lb_method is defined
      - item.monitors is defined
      - item.monitor_type is defined
      - item.monitor_type in [ "and_list", "single", "m_of_n" ]
    quiet: yes
  loop: "{{ f5_ltm_pools }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - f5_ltm_pools is defined

- name: test if f5_ltm_pool_members is set correctly
  assert:
    that:
      - f5_ltm_pool_members is iterable
    quiet: yes
  when:
    - f5_ltm_pool_members is defined

- name: test if item in f5_ltm_pool_members is set correctly
  assert:
    that:
      - item.name is defined
      - item.member is defined
      - item.member is iterable
    quiet: yes
  loop: "{{ f5_ltm_pool_members }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - f5_ltm_pool_members is defined

- name: test if f5_ltm_virtual_servers is set correctly
  assert:
    that:
      - f5_ltm_virtual_servers is iterable
    quiet: yes
  when:
    - f5_ltm_virtual_servers is defined

- name: test if item in f5_ltm_virtual_servers is set correctly
  assert:
    that:
      - item.name is defined
      - item.pool is defined
      - item.destination is defined
      - item.port is number
      - item.port > 0
      - item.port < 65536
      - item.enable_vlans is defined
      - item.all_profiles is defined
      - item.all_profiles is iterable
      - item.snat is defined
      - item.snap in [ "dhcp", "reject", "internal", "none", "automap" ]
    quiet: yes
  when:
    - f5_ltm_virtual_servers is defined
