---
# tasks file for f5_ltm
- name: set hostname
  bigip_hostname:
    hostname: "{{ f5_ltm_hostname }}"
  when:
    - f5_ltm_hostname is defined

- name: set timezone
  bigip_device_ntp:
    timezone: "{{ f5_ltm_timezone | default(omit) }}"
    ntp_servers: "{{ f5_ltm_ntp_servers | default(omit) }}"
  when:
    - f5_ltm_timezone is defined or
      f5_ltm_ntp_servers is defined

- name: create nodes
  bigip_node:
    provider: "{{ f5_ltm_provider }}"
    name: "{{ item.name }}"
    host: "{{ item.host }}"
  loop: "{{ f5_ltm_nodes }}"
  when:
    - f5_ltm_nodes is defined

- name: create pools
  bigip_pool:
    provider: "{{ provider }}"
    name: "{{ item.name }}"
    lb_method: "{{ item.lb_method }}"
    monitors: "{{ item.monitors }}"
    monitor_type: "{{ item.monitor_type }}"
  loop: "{{ f5_ltm_pools }}"
  when:
    - f5_ltm_pools is defined

- name: include pool_member.yml
  include: pool_member.yml
  loop_control:
    label: pool_member
  loop: "{{ f5_ltm_pool_members }}"
  when:
    - f5_ltm_pool_members is defined

- name: ADD VIRTUAL SERVER
  bigip_virtual_server:
    provider: "{{ provider }}"
    name: "{{ item.name }}"
    destination: "{{ item.destination }}"
    port: "{{ item.port }}"
    enabled_vlans: "{{ item.enable_vlans }}"
    all_profiles: "{{ item.all_profiles }}"
    pool: "{{ item.pool }}"
    snat: "{{ item.snat }}"
  loop: "{{ f5_ltm_virtual_servers }}"
  when:
    - f5_ltm_virtual_servers is defined
